### ISSUE TITLE
Fill Range with known start cell only

### ISSUE THREAD

**Issue by electricalbah** [dtjohnson/xlsx-populate#103]
There is an example where you have to specify the range to fill
const r = workbook.sheet(0).range("A1:C3");
 
// Set the values using a 2D array:
r.value([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]);

I don't know if this API already exist but I think it will be great to just specify the start cell and the range automatically calculated from the array

XlsxPopulate.copyArray(myArray, workbook.sheet(0).cell("A7"))   //where A7 is the start cell

**Comment by dtjohnson** [comment]
It's a good idea. I wonder if we could just overload the [Cell.value setter](https://github.com/dtjohnson/xlsx-populate#cellvaluevalue--cell) some more. So if you call it with an array it assume you want to fill from there.

Something like: `cell.value([[1, 2, 3], [4, 5, 6]]);`

That would also let you fill a sheet pretty quickly too: `sheet.cell("A1").value([...])`

I like this better than some new fill method because we could leverage the same pattern for style and formula too.

**Comment by dtjohnson** [comment]
Just published v1.13.0 with this feature. Works for value and styles:
```js
cell.value([[1, 2, 3], [4, 5, 6]]);
cell.style("bold", [[true, false, true], [false, true, false]]);
```

**Comment by Anil-Kumar05** [comment]
Can I use an array of objects with key-value pairs?

**Comment by electricalbah** [comment]
Perfect
Thanks for this feature
