### ISSUE TITLE
Bug with List data validation for pure input

### ISSUE THREAD

**Issue by Jia265** [dtjohnson/xlsx-populate#104]
Here's the scenario:
```
        sheet.cell("B2").dataValidation({ type: 'list',
          allowBlank: false,
          showInputMessage: false,
          prompt: '',
          promptTitle: '',
          showErrorMessage: false,
          error: '',
          errorTitle: '',
          operator: '',
          formula1: 'test1',
          formula2: ''
        });
```

This works fine, 

But once I change formula1 to be multiple items, like on the example on the npmjs page

```
{
    type: 'list',
    allowBlank: false, 
    showInputMessage: false,
    prompt: false,
    promptTitle: 'String',
    showErrorMessage: false,
    error: 'String',
    errorTitle: 'String',
    operator: 'String',
    formula1: 'Item1,Item2,Item3,Item4',//Required
    formula2: 'String'
}
```

I get error when I open the excel sheet. 

When I went back to the first try that worked with a single item, I found that in the data validation box for excel there was this entry for
Source
=test1

Looks like the equal is appended to whatever formula1 is. Which won't work for a static list.

**Comment by alandoyle95** [comment]
Hmm... I'll look into this..

**Comment by Jia265** [comment]
Hey alandoyle95, thanks for responding. I just also wanted to add, the first case works fine isn't exactly right.

The first case just doesn't error out when I try to open the excel sheet, it doesn't have any items for the actual dropdown. And when I try to edit the dropdown value in the excel sheet, I would get an error for invalid range, regardless of whether or not I use a range.

**Comment by alandoyle95** [comment]
ok, so it looks like its a bug due to how the object gets converted back into XML...
the list from an excel that you create with dataValidation of a list just like the example has quotes around it.
however, the xlsx-populate does not put the quotes...

if you just try to bypass this. by adding in the `"` into the list... it removes them upon writing it to the file.

@dtjohnson  has anything changed with the XML Builder? that pretty much the only thing I can think that could cause this.. because this was working just fine back when I did the pull request. passed the tests and everything.

**Comment by alandoyle95** [comment]
OK, so here is a workaround for the time being... 
if you do this..

```
{
    type: 'list',
    allowBlank: false,
    showInputMessage: false,
    prompt: false,
    promptTitle: '',
    showErrorMessage: false,
    error: '',
    errorTitle: '',
    operator: '',
    formula1: '\"Item1,Item2,Item3,Item4\"',
    formula2: ''
}
```

**Comment by Jia265** [comment]
Thanks @alandoyle95 , that works. 

My only concern is that will this also work even after the bug is fixed?

**Comment by alandoyle95** [comment]
probably not, but at this time I'm not entirely sure the best way to fix this bug. because if its a Range thats in the value it cant have the quotes.. or it just thinks that's an option in the drop-down. and does not use the range...

currently, the only thing I can think of is if `formula1` has a `,` in it then it would wrap it with `\" \"` BUT, that will not work if its a dropdown with only one item in it as there would not be a `,` in the formula.

**Comment by Jia265** [comment]
ah okay thanks, I'll stick with using a formula for now then, and populate data on a hidden sheet. 

I do appreciate the quick response, I wasn't sure if it was me not using the library properly or an actual bug.

**Comment by alandoyle95** [comment]
No Problem 😄 This Repo is what my company currently run off of... so I like to try to help maintain it 😄 

I have 500+ excel forms a day that get modified by this repo

**Comment by dtjohnson** [comment]
Sorry for the delay. The formula for a static list of values is the string `'"foo,bar,baz"'` as @alandoyle95 pointed out.
The double-quotes are required. (But the double-quotes do not need to be escaped.)
Without the double-quotes, `foo,bar,baz` is the formula of the union of 3 cells named `foo`, `bar`, and `baz`.

So this is all working as expected. However, it might be helpful to support setting the value with an array of strings as a shortcut for this.

**Comment by alandoyle95** [comment]
You can set it with an array of strings, same bug persists due to `formula
= user input` and it not dealing with adding the quotes, and if you don't
escape them when the xml get generated the quotes get removed.

**Comment by dtjohnson** [comment]
That can't be true. Open a terminal and run
```js
'"foo"' === '\"foo\"'
```
You'll get `true`, proving they are identical and the escapes are unnecessary.

The following data validation works for me:
```js
workbook.sheet("Sheet1").cell("A1").dataValidation({
    type: "list",
    formula1: '"foo,bar,baz"'
});
```


I don't see the setter for array value... I meant something like
```js
workbook.sheet("Sheet1").cell("A1").dataValidation({
    type: "list",
    formula1: ["foo", "bar", "baz"]
});
```
which doesn't execute or something like this
```js
workbook.sheet("Sheet1").cell("A1").dataValidation(["foo", "bar", "baz"]);
```
which results in an empty formula as it tries to read non-existent properties off of the array.

**Comment by alandoyle95** [comment]
Yes, you will get true. BUT when the file gets written to XML, the `"` get removed. UNLESS you have them escaped.

**Comment by dtjohnson** [comment]
It returns `true` because the two strings are identical. And anything you do with the strings will be identical. Escaping double-quotes within single quotes is unnecessary (and vice versa). The JavaScript engine just strips the useless escapes out. There is even an [eslint rule](https://eslint.org/docs/rules/no-useless-escape) that flags these.

Since the escapes are unnecessary, the XML and XLSX files generated by xlsx-populate are identical. Here's code demonstrating that:
```js
const XlsxPopulate = require('xlsx-populate');

(async () => {
    // Create two workbooks.
    const workbook1 = await XlsxPopulate.fromBlankAsync();
    const workbook2 = await XlsxPopulate.fromBlankAsync();

    // Set data validation.
    workbook1.activeSheet().cell("A1").dataValidation('"foo,bar,baz"');
    workbook2.activeSheet().cell("A1").dataValidation('\"foo,bar,baz\"');

    // Convert to buffers
    const buffer1 = await workbook1.outputAsync();
    const buffer2 = await workbook2.outputAsync();

    // Compare bytes. This will return true as they are identical.
    console.log(buffer1.equals(buffer2));

    // Write them to file.
    await workbook1.toFileAsync("out1.xlsx");
    await workbook2.toFileAsync("out2.xlsx");
})();
```
The buffer comparison returns `true` as the two generated workbooks (one with the escapes and one without) are byte-for-byte identical. You can also test both output files and see that they both show functional drop down lists in cell A1.
