### ISSUE TITLE
Issues while upgrading the package for Angular 6++?

### ISSUE THREAD

**Issue by tintran253** [dtjohnson/xlsx-populate#130]
Hi, 

It's work perfect under v.6. But after moment update to latest version of Angular, issues happen with **fs**, **crypto**, **stream** and **Buffer** ... seems from Node libraries.

Does anyone have same issues and already solve it, please? 

Thanks in advance.

**Comment by tintran253** [comment]
Solved by using /browser instead of /lib ...

But need to be confirmed if its right. 

Thanks.

**Comment by tintran253** [comment]
It happens **JQc is not defined**

any ideas please ?

**Comment by smoke** [comment]
I am also struggling with that and looking for solutions.

**Comment by smoke** [comment]
I have some progress and I am working on a PR, but I am having issues. 

Meanwhile here is what I found and the current status:
 - Angular 6 as described in https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814 and the PR is https://github.com/angular/angular-cli/pull/9812 now requires browser specific builds of npm packages - so that they don't use nodejs specifics e.g. `fs`, `net`, etc. - this is why we need to use the `browser/xlsx-populate*` built files
 - there is a proper way using https://docs.npmjs.com/files/package.json#browser to point out the browser specialized built of the package, however due to https://github.com/browserify/browserify/issues/1746#issuecomment-389134320 I am having issues building the package
 - in addition the `JQc is not defined` is caused as pointed here https://github.com/dtjohnson/xlsx-populate/issues/124 by bug https://github.com/mishoo/UglifyJS2/issues/2783 and the `browser/xlsx-populate*` need to be rebuild with the new version of uglify-js - once done this would solve at least 2-3 opened issues here

**Comment by dtjohnson** [comment]
Please try with v1.17.0. There is also a non-minified version available now.

**Comment by smoke** [comment]
I confirm the `JQc is not defined` problem is fixed with the new version, however I still had to point to the specific version of xlsx-populate that I wanted to use in my `tsconfig.app.json` like so:
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": [],
    "paths": {
      "xlsx-populate": [
        "../node_modules/xlsx-populate/browser/xlsx-populate-no-encryption.min.js"
      ]
    }
  },
  "angularCompilerOptions": {
    "preserveWhitespaces": true
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

**Comment by sonicwong** [comment]
@trtin 
>> Solved by using /browser instead of /lib

I am using angular 8. After add "../node_modules/xlsx-populate/browser/xlsx-populate-no-encryption.min.js" to tsconfig.app.json, still same error:

ERROR in ./node_modules/xlsx-populate/lib/Workbook.js
Module not found: Error: Can't resolve 'fs' in '/Users/sonic/Documents/admin/node_modules/xlsx-populate/lib'

Thanks.

**Comment by Akxe** [comment]
@smoke It solved the problem with angular not compiling, but it did mess up my type declarations :/
