### ISSUE TITLE
insert value and make it read only 'cell'

### ISSUE THREAD

**Issue by savantAnalytics2018** [dtjohnson/xlsx-populate#168]
How can we make range of cell of Read only (after inserting text or any content).

**Comment by eddiecorrigall** [comment]
Hi Saif,

Read-only cell ranges do not appear to be part of the xlsx standard. Please see,
https://msdn.microsoft.com/en-us/library/dd922181(v=office.12).aspx

If you are familiar with Google Docs, this feature is called "protected sheets & ranges", and does not appear to export/translate. This is clear if you inspect the sheet xml via the following instructions,
1. Create a sheet on Google Docs
2. Right-click a cell, and click "protect range..."
3. Setup as desired
4. Export using File > "Download as" > "Microsoft Excel (.xlsx)"
5. Rename downloaded .xlsx file, and append a .zip extension, ie filename.xlsx to filename.xlsx.zip
6. Unzip the file
7. Explore the newly unzipped folder, and review xl/worksheets/sheet1.xml

You will see that there is no special read-only information stored in sheet1.xml or any other file. Google Docs has their own read-only internal file format, which xlsx does not support.

I have not worked on this project for quite some time, and my only contact is @dtjohnson. ~Try reaching out to him, or open an issue on GitHub to seek advice.~ I imagine since this is a non-standard request that it will not become part of the code base on GitHub. You will likely need to modify your web application to support a read-only feature just as Google Docs has done.
