### ISSUE TITLE
Defined Names not working

### ISSUE THREAD

**Issue by jloiola** [dtjohnson/xlsx-populate#261]
Here's a simple jsfiddle

https://jsfiddle.net/z8Lbceaq/

TypeError: Cannot read property 'value' of undefined

**Comment by tmcmah1** [comment]
A couple of notes: 

- Since it was starting with a blank workbook, there were no preexisting defined names.
- The docs seem to suggest that a definedName with a space would work, but it doesn't in my version of Excel.  Can't have spaces in the name.

So, this worked for me:
```javascript
// Create a definedName called 'newName': 
// Note that the definedName is attached to the *workbook* instead of the sheet
workbook.definedName("newName", "Sheet1!$B$2"); 
// less common, but also works: workbook.sheet(0).definedName("newName", "Sheet1!$B$2"); 

// then set the value
workbook.definedName("newName").value("New Value"); 
```
https://jsfiddle.net/d2xw1ygz/1/
