### ISSUE TITLE
Images always resized along with columns

### ISSUE THREAD

**Issue by maxjanisse** [dtjohnson/xlsx-populate#27]
Greetings and Happy Friday! This time I have a _real_ bug for you, hopefully you can help me out once more. Using the provided example file and code snippet you should be able to see the problem I'm having.

If the source spreadsheet contains an image, and then the widths of the columns it overlaps are manipulated, the image will be scaled as well.  However, there are options within Excel that allow users to explicitly determine the behavior of image resizing with respect to column manipulation (_right-click image -> "Size and Properties" -> "Properties" section_).  In this case, I have set the image properties to "Don't move or size with cells", so I'm _hoping_ that there is a way for that setting to be taken into account.

Hopefully this is enough to get started. Please let me know if I can be of any more help.

Thanks!

[example-with-image.xlsx](https://github.com/dtjohnson/xlsx-populate/files/868613/example-with-image.xlsx)

```
const xlsxPopulate = require('xlsx-populate');

xlsxPopulate.fromFileAsync('./example-with-image.xlsx')
            .then(workbook => {
                const sheet = [
                    [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]
                ];

                const worksheet = workbook.sheet(0);

                // Insert sheet data
                const rowsCount = (sheet.length - 1);
                const columnCount = (sheet[0].length - 1);
                const cellStartInsert = workbook.find("${data}")[0];
                const cellEndInsert = cellStartInsert.relativeCell(rowsCount, columnCount);
                const addrStartCell = cellStartInsert.address();
                const addrEndCell = cellEndInsert.address();
                const rangeForSheet = worksheet.range(`${addrStartCell}:${addrEndCell}`);
                rangeForSheet.value(sheet);
                
                // Auto-size column widths and set heights to rows
                const addrHeaderEnd = cellStartInsert.relativeCell(0, columnCount).address();
                const rangeHeader = worksheet.range(`${addrStartCell}:${addrHeaderEnd}`);
                rangeHeader.forEach((cell, ri, ci, range) => {
                    const cellColumnLast = cell.relativeCell(rowsCount, 0);
                    const addrColumnFirst = cell.address();
                    const addrColumnLast = cellColumnLast.address();

                    const columnWidth = 25;

                    const addrColumn = cell.column().address().split(':')[0];
                    worksheet.column(addrColumn).width(columnWidth);
                });

                workbook.toFileAsync('./out.xlsx');
            });
```

**Comment by dtjohnson** [comment]
First off, thanks for the extremely helpful error report! Having the sample code and template demonstrating the issue is extremely helpful!

Second, just a couple tips. The Sheet.range method also accepts start cell and end cell. See the [API docs here](https://github.com/dtjohnson/xlsx-populate#Sheet+range). So you could use that instead of concatenating the cell addresses into a range address. And instead of using Workbook.find, you could use [Defined Names](https://github.com/dtjohnson/xlsx-populate#defined-names) to identify a cell. It is more performant than searching for all matches of a string.

Now to your issue. I do see the issue you are having, but the news isn't very good. It looks like the image is referenced in the XLSX zip in xl/drawings/drawing1.xml. There is a block of XML that seems to be responsible for positioning:
```xml
<xdr:from>
	<xdr:col>1</xdr:col>
	<xdr:colOff>0</xdr:colOff>
	<xdr:row>1</xdr:row>
	<xdr:rowOff>1</xdr:rowOff>
</xdr:from>
<xdr:to>
	<xdr:col>9</xdr:col>
	<xdr:colOff>0</xdr:colOff>
	<xdr:row>8</xdr:row>
	<xdr:rowOff>129541</xdr:rowOff>
</xdr:to>
```
Looks like references to starting/ending row/columns with some offset (not sure of the units).

When you resize the columns with xlsx-populate, it doesn't touch this drawing.xml file at all. So the 'to' xml node still refers to column 9, which is why the image gets resized.

If you resize the column in Excel, those XML nodes change to something like:
```xml
<xdr:from>
	<xdr:col>1</xdr:col>
	<xdr:colOff>0</xdr:colOff>
	<xdr:row>1</xdr:row>
	<xdr:rowOff>1</xdr:rowOff>
</xdr:from>
<xdr:to>
	<xdr:col>7</xdr:col>
	<xdr:colOff>142875</xdr:colOff>
	<xdr:row>8</xdr:row>
	<xdr:rowOff>129541</xdr:rowOff>
</xdr:to>
```
Notice that Excel updated the 'to' node in such a way to keep the image size the same.

This is unfortunately a non-trivial issue to fix as there is no current drawing support in xlsx-populate. We'd have to support parsing/writing the drawing.xml files. Not opposed to doing it at some point, but it doesn't look very simple.

The only _hack_ I could think of for you to try is to change the size of another column in the range covered by the image to offset the change. So if you increase column A from 10 to 15, reduce column B from 10 to 5. Not ideal, but I don't have any more clever ideas.

**Comment by maxjanisse** [comment]
My pleasure! I'm glad it was enough information to perform an investigation.  

Thank you very much for the thorough explanation on the issue from your perspective.  It's too bad that there isn't a fix for this possible in the short term but I kinda figured that would be the case.  Your "hack" would definitely fix the issue but, sadly, my _actual_ resize logic determines the column widths based on the size of the content within them, so offsetting the overall delta wouldn't work out in the end.  Oh well, I'll figure something out.

Also, I really appreciate the suggestions, I'll be implementing those shortly, should help clean up my code a bit.

Thanks for all your support.  Really appreciate it.
