### ISSUE TITLE
row insertion

### ISSUE THREAD

**Issue by lap123** [dtjohnson/xlsx-populate#38]
Is there a way to insert a row from a given row position?
Thank you.

**Comment by dtjohnson** [comment]
There is no built-in way to do currently this because it turns out to be very hard to preserve all of the existing formula, chart, etc. references when doing so. Maybe one day we'll have it.

For now you could try moving the values down with something like:
```js
const insertRowNumber = 5;
const lastRowNumber = 20;

// Get the current values
const moveValues = sheet.range(insertRowNumber, 1, lastRowNumber, 50).values();

// Copy them to one row down
sheet.range(insertRowNumber + 1, 1, lastRowNumber + 1, 50).values(moveValues);

// Clear the insert row
sheet.range(insertRowNumber, 1, insertRowNumber, 50).clear();
```

You'll have to handle styles separately.

**Comment by lap123** [comment]
That's very helpful.
Thank you.

**Comment by thearabbit** [comment]
I tried error with `.values()`, but work with `.value()`

**Comment by thearabbit** [comment]
Now it work, but have problem with `styles: merge, border...`
