### ISSUE TITLE
Malfunction in applying style after 3300 rows

### ISSUE THREAD

**Issue by vijaybalans** [dtjohnson/xlsx-populate#71]
If apply a style like Bold, it works fine up-to 3300 rows. After that, the style doesn't get applied, but on focus, it shows Bold in the toolbar

**Comment by alandoyle95** [comment]
is this inside of excel? because excel HATES going above 2500 ish rows and causes all sorts of problems.. if the bold is in the toolbar then the program is working fine, but excel is that one that is not showing it.

**Comment by vijaybalans** [comment]
Yes, the excel is working fine till 3200 lines. Only after that, the problem in styling occurs. How should that be fixed?

**Comment by alandoyle95** [comment]
it cant be, that's excel freaking out because of the number of rows. Microsoft would need to fix that. or you would need to switch to a better data storage system like MySQL and use something else to show the data

**Comment by dtjohnson** [comment]
I suspect this may be due to the inefficient way that xlsx-populate currently handles styles. Duplicate styles are unfortunately all replicated, which may be causing some odd performance behavior in Excel. The workaround is to apply the styles to entire rows and/or columns or to pre-style a template.
