### ISSUE TITLE
.xlsm support

### ISSUE THREAD

**Issue by 271bibi** [dtjohnson/xlsx-populate#76]
Hi, does this package also support changing cells in .xlsm files? Thank you!

**Comment by dtjohnson** [comment]
Yep. It should work.

**Comment by UMAknow-Patrick** [comment]
Hi, I tried Generate Blob in the Browser Demo with a simple .xlsm file (no macros in it) but when I opened the generated file, I got this error:
Excel cannot open the file because the file format or file extension is not valid
![2018-04-13 11_34_50-excel](https://user-images.githubusercontent.com/20410244/38744091-deba1b96-3f0e-11e8-8baf-9dae20e9d965.png)
I also tried in my code with no success. Any hint ?
Thank you,

**Comment by tEgRaT** [comment]
@UMAknow-Patrick did you ever get an answer for this? I'm experiencing the same thing.

**Comment by JayCole4Byers** [comment]
I tried .xlsm & .xls, both with macros embedded and got the same error. It would be nice if they added support for these file types too. But this is the only project I've found that keeps the Formatting. I will add the macros to my personal workbook and call them from there.

**Comment by liji123** [comment]
@UMAknow-Patrick You need to change the extension name from "xlsx" to "xlsm", the file could be opened then. However, I found another issue, after this step, my embedded macro cannot run and Excel prompts security problem like this:
![image](https://user-images.githubusercontent.com/14195451/44022165-6ae3d8a4-9f19-11e8-8c98-b4ad8a3c2370.png)

**Comment by vic379** [comment]
Hi, is there an option to read a protected xlsm file? I'm having issues trying to do it. When I try I get:(node:10836) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Non-whitespace before first tag.

I'm using this code: 
XlsxPopulate.fromFileAsync(pathFile, {password: 'xxx'})
    .then(workbook => {
      console.log(workbook);
    });

I hope you can guide me. Thank you.
