### ISSUE TITLE
Detect date?

### ISSUE THREAD

**Issue by jbrecht** [dtjohnson/xlsx-populate#92]
Is there a general way to detect whether a cell is a date? (or more broadly, what its type is meant to be in general - number, string, boolean, date, etc...)

We get partway there by checking the numberFormat style, but there are still a variety of values for this that might correspond to a cell being a date.

**Comment by dtjohnson** [comment]
Unfortunately, no. If there was a reliable way to do this we would've made the value getter return a date. Dates are stored in Excel as floats with a number format to make it look like a date. Other than number format, you could check if it's a number in a reasonable range as the value is roughly the number of days since Jan 1, 1900.
